<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto

namespace GPBMetadata;

class Greet
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa7010a0b67726565742e70726f746f12056772656574221c0a0c48656c6c6f52657175657374120c0a046e616d65180120012809221d0a0a48656c6c6f5265706c79120f0a076d657373616765180120012809323d0a074772656574657212320a0853617948656c6c6f12132e67726565742e48656c6c6f526571756573741a112e67726565742e48656c6c6f5265706c79420daa020a47727063536572766572620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

